name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            build-essential python3-pip

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer==1.5.0

      - name: Build APK (Kivy / Buildozer)
        run: |
          export PATH=$PATH:~/.local/bin
          export CI=1
          yes | buildozer -v android debug --allow-root

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
